# Configuration options for the resource pack
# READ SETUP GUIDE: https://xenondevs.xyz/docs/nova/admin/setup/#step-2-resourcepack-hosting
resource_pack:
  # The auto uploader automatically uploads the resource pack after generation.
  # READ SETUP GUIDE: https://xenondevs.xyz/docs/nova/admin/setup/#automatic-resource-pack-hosting
  auto_upload:
    enabled: false
    
  # Settings affecting the resource pack prompt
  prompt:
    # The resource pack prompt message
    message: §bNova Resource Pack
    # Whether players are forced to accept the resource pack
    force: true
    # Activates the 'nova.misc.resourcePack.bypass.force' permission, with which players will still get the resource pack prompt, but won't be forced to accept it.
    # This permission is disabled by default, so players with *-permissions will not accidentally bypass it.
    enableForceBypassPermission: false
    # Activates the 'nova.misc.resourcePack.bypass.prompt' permission, with which players will not get the resource pack prompt.
    # This permission is disabled by default, so players with *-permissions will not accidentally bypass the prompt.
    enablePromptBypassPermission: false
  # Settings affecting how the resource pack is generated.
  generation:
    # The resource pack description.
    description: Nova (%s asset pack(s), %s base pack(s))
    # Resource packs that should be merged with Nova's resource pack.
    # More information about base packs can be found in our documentation: https://xenondevs.xyz/docs/nova/admin/setup/#optional-resourcepack-merging
    base_packs: [ ]
    # The zip compression level, ranging from 0 (no compression) to 9 (best compression) or -1 for default.
    compression_level: -1
    # If the generation process should take place entirely in memory. This increases memory usage but improves generation speed.
    in_memory: true
    # Protection settings for the resource pack.
    protection:
      # Renames resource pack textures and models.
      obfuscate: false
      # Protects the zip from being opened in normal zip programs.
      corrupt_entries: false
    # Settings regarding the generation of font files.
    font:
      # If moved versions of the default font should use the legacy_unicode providers instead of Minecraft's default bitmap characters.
      # This option affects the generated moved default fonts the same way as the "Force Unicode Font" button in Minecraft's language settings does the default font.
      # This also affects the calculated char sizes for all fonts that use both legacy_unicode and bitmap providers.
      force_unicode_font: false
      # A list of fonts that should not have moved versions generated.
      # Generally, all custom fonts from base packs that don't require moved versions (i.e. are not shown in the boss bar) should be added here.
      moved_font_blacklist: [ ]
    # A list of file extensions that shouldn't be excluded from the resource pack, even though they're not vanilla resource pack files.
    whitelisted_file_types: [ ]
    # Excludes files from the resource pack. Excluding files will decrease the size of your resource pack but might also break some features.
    # More information about resource filters can be found in our documentation: https://xenondevs.xyz/docs/nova/admin/configuration/#resource-filters
    resource_filters: [ ]
    # Whether Minecraft assets should be downloaded from GitHub or Mojang's API.
    # GitHub is faster since it's a single zip file. If you're unable to access GitHub, change this to "mojang".
    minecraft_assets_source: github
    # If Nova is allowed to use solid block states (e.g. mushroom, noteblock) when addons request it.
    # Please read the following documentation page before change this value: https://xenondevs.xyz/docs/nova/admin/compatibility/troubleshooting/#solid-blocks
    use_solid_blocks: true
  # If players currently loading the resource pack should be frozen.
  freeze_loading_players: false

# The render distance for fake (packet-based) entities from Nova, in chunks.
# Note that the render distance is also limited by the entity render distance of the client.
entity_render_distance:
  min: 1
  max: 6
  default: 4

overlay:
  actionbar:
    # Enable / disable all action bar overlays.
    enabled: true
  bossbar:
    # Enable / disable all boss bar overlays.
    # You will need to regenerate the resource pack after changing this value.
    enabled: true
    # How many invisible boss bar should be sent to the player.
    amount: 20
    # If the boss bars should be sent after the player confirms that the server resource pack has been loaded.
    # !!! THIS WILL CAUSE ISSUES IF YOU'RE NOT USING NOVA'S FORCED RESOURCE PACK !!!
    send_bars_after_resource_pack_loaded: false
    # A list of colors for which the boss bar should not be rendered.
    # Possible colors: pink, blue, red, green, yellow, purple, white
    invisible_colors: [ ]
    # Settings affecting vanilla boss bars.
    vanilla_bars:
      # Settings affecting the positioning of vanilla boss bars.
      positioning:
        # The minimum distance from the boss bar above, in pixels (affected by gui scale).
        margin_top: 14
        # The minimum distance from the boss bar below, in pixels (affected by gui scale).
        margin_bottom: 0

waila:
  # Enable / disable the WAILA overlay.
  enabled: true
  # Settings affecting the position of the WAILA overlay.
  positioning:
    # The minimum distance from the overlay above, in pixels (affected by gui scale).
    margin_top: 5
    # The minimum distance from the overlay below, in pixels (affected by gui scale).
    margin_bottom: 5
    # The matchers for bars that should be below WAILA.
    # See: https://xenondevs.xyz/docs/nova/admin/configuration/#waila-positioning
    above:
      - type: index
        index: 0
    # The matchers for bars that should be above WAILA.
    # See: https://xenondevs.xyz/docs/nova/admin/configuration/#waila-positioning
    below: [ ]
  # The interval for checking if a player is looking at a new block.
  pos_update_interval: 1
  # The interval for updating the overlay, regardless if the player is still looking at the same block.
  # Updating the overlay under these circumstances is still required for displaying the tool matching, energy, etc. properly.
  data_update_interval: 5
  # A list of namespaced ids representing the blocks that should not be shown in WAILA.
  # Allows wildcard patterns, e.g. "minecraft:*_ore" or "minecraft:*"
  blacklisted_blocks: [ ]

world:
  # Settings affecting block breaking.
  block_breaking:
    # If client-side predictions should be allowed for breaking vanilla blocks with vanilla tools.
    clientside_predictions: true
    # The block break cooldown, in ticks.
    break_cooldown: 5
  # If unknown blocks (e.g. blocks of addons that couldn't be loaded) should be deleted.
  delete_unknown_blocks: false

# Performance options
performance:
  # Nova's executor caps the amount of threads that are allowed to run simultaneously in order to prevent OutOfMemoryErrors.
  nova_executor:
    # If enabled, Nova's own executor will be used. Otherwise, Bukkit's scheduler system is used.
    enabled: true
    # The amount of threads to be started.
    threads: 200
  # If all char sizes should be loaded on startup. This will increase startup time but prevent lags when initially accessing char sizes.
  load_char_sizes_on_startup: false
  # If backup files should be created while saving Nova regions
  region_backups: true
  # If excess items should be dropped on the ground.
  drop_excess_on_ground: true
  # If block break particles should be displayed.
  block_break_effects: true

# Default transfer rates for networks when tile entities are directly connected.
network:
  energy:
    default_transfer_rate: 9223372036854775807
  item:
    default_transfer_rate: 2147483647
  fluid:
    default_transfer_rate: 9223372036854775807

# If metric prefixes should be used to display energy and fluids (e.g. kJ, MJ, GJ or B, kB, MB)
use_metric_prefixes: false

update_reminder:
  # If update reminders should be shown.
  enabled: true
  # The amount of ticks passed between update checks.
  interval: 12000

debug:
  # The chunk reload watcher will print stack traces if repeated chunk loads and unloads are detected.
  watch_chunk_reloads: false
  # If other plugins should be allowed to overwrite the results of Nova recipes.
  allow_craft_result_overwrite: false
  # Whether the background texture of tooltips for ui items with empty names should be hidden.
  # This option requires regenerating the resource pack.
  hide_empty_tooltip: true