name: Build Documentation

on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Run BuildTools
        run: . .github/scripts/buildtools.sh

      - name: Run Dokka
        run: ./gradlew dokkaHtmlMultiModule

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: build/dokka/htmlMultiModule
